import { useEffect, useState } from "react";
import { Alert, Button, Card, Checkbox, Input, Radio, Select, Table } from "antd";
import { createFactorBatch, evaluateFactorHoldout, freezeFactorRepresentatives, getFactorBatchSummary, getFactorCatalog, getFactorCorrelation, getIndexSnapshot, listDataHubReleases, type FactorBatchSummary, type FactorCatalogRow, type FactorCorrelation, type ReleaseSummary } from "../api";

export function FactorLab() {
  const [rows, setRows] = useState<FactorCatalogRow[]>([]); const [error, setError] = useState(""); const [members, setMembers] = useState(""); const [release, setRelease] = useState(""); const [releases,setReleases]=useState<ReleaseSummary[]>([]); const [batch, setBatch] = useState(""); const [summary, setSummary] = useState<FactorBatchSummary | null>(null); const [poolType,setPoolType]=useState("CUSTOM_STATIC_POOL"); const [indexCode,setIndexCode]=useState("000300.SH"); const [snapshotDate,setSnapshotDate]=useState("2022-07-01"); const [startDate,setStartDate]=useState("2020-01-01"); const [endDate,setEndDate]=useState("2024-12-31"); const [horizons,setHorizons]=useState<number[]>([1,5,20]); const [splitRatios,setSplitRatios]=useState("0.6,0.2,0.2"); const [correlation,setCorrelation]=useState<FactorCorrelation | null>(null); const [selected,setSelected]=useState<number[]>([]); const [reasons,setReasons]=useState<Record<string,string>>({}); const [frozen,setFrozen]=useState(false); const [holdout,setHoldout]=useState<Record<string,unknown> | null>(null);
  useEffect(() => { getFactorCatalog().then(r => setRows(r.factors)).catch(e => setError(String(e))); }, []);
  useEffect(() => { listDataHubReleases().then(r=>{setReleases(r.releases);setRelease(r.current_release_id)}).catch(e=>setError(String(e))); }, []);
  const ready = rows.filter(r => r.group === "price_volume");
  const start = async () => { try { let selected=members.split(/[\s,]+/).filter(Boolean); if(poolType!=="CUSTOM_STATIC_POOL") selected=(await getIndexSnapshot(release,indexCode,snapshotDate)).members; const r = await createFactorBatch({ release_id: release, members:selected, start_date: startDate, end_date: endDate, alpha_ids: ready.map(x => x.alpha_id), horizons, split_ratios: splitRatios.split(",").map(Number), pool_type: poolType, snapshot_date: poolType==="CUSTOM_STATIC_POOL"?null:snapshotDate }); setBatch(r.experiment_id); setCorrelation(null); setSelected([]); setFrozen(false); setHoldout(null); } catch (e) { setError(String(e)); } };
  useEffect(() => { if (!batch) return; let alive=true; const poll=async()=>{ try { const r=await getFactorBatchSummary(batch); if(alive) setSummary(r); } catch(e){ if(alive)setError(String(e)); } }; void poll(); const timer=setInterval(poll,2000); return()=>{alive=false;clearInterval(timer)}; },[batch]);
  return <Card title="FactorLab" extra={<span>RAW 工程研究 · 非严格 PIT</span>}>
    {error && <Alert type="error" message={error} showIcon />}
    <p>共 {rows.length} 个 Alpha101 公式；默认可选择 {ready.length} 个量价项。研究和验证段完成后，保留段在人工冻结代表因子前不可访问。</p>
    <Select placeholder="固定 release" value={release || undefined} onChange={setRelease} options={releases.map(r=>({value:r.release_id,label:`${r.release_id} · base ${r.base_commit.slice(0,8)} · supp ${(r.supplemental_commit||"—").slice(0,8)}`}))} style={{width:460,marginBottom:8}} />
    <Input value={startDate} onChange={e=>setStartDate(e.target.value)} placeholder="开始日期 YYYY-MM-DD" style={{width:180,marginRight:6}} /><Input value={endDate} onChange={e=>setEndDate(e.target.value)} placeholder="结束日期 YYYY-MM-DD" style={{width:180}} />
    <Checkbox.Group value={horizons} onChange={v=>setHorizons(v as number[])} options={[1,5,20].map(x=>({label:`${x} 日标签`,value:x}))} style={{margin:"8px 12px"}} /><Input value={splitRatios} onChange={e=>setSplitRatios(e.target.value)} placeholder="研究,验证,保留比例，如 0.6,0.2,0.2" style={{width:260}} />
    <Radio.Group value={poolType} onChange={e=>setPoolType(e.target.value)} options={[{label:"自定义静态池",value:"CUSTOM_STATIC_POOL"},{label:"指数静态快照池（非 PIT）",value:"INDEX_SNAPSHOT_STATIC_POOL"}]} style={{marginBottom:8}} />
    {poolType==="CUSTOM_STATIC_POOL" ? <Input.TextArea placeholder="自定义静态股票池：以逗号或空格分隔代码，至少 20 只" value={members} onChange={e => setMembers(e.target.value)} rows={2} /> : <><Input value={indexCode} onChange={e=>setIndexCode(e.target.value)} placeholder="指数代码" /><Input value={snapshotDate} onChange={e=>setSnapshotDate(e.target.value)} placeholder="快照日期 YYYY-MM-DD" style={{marginTop:6}} /><Alert type="warning" showIcon message="静态指数快照池，不是历史 PIT 成分池" style={{marginTop:6}} /></>}
    <Button type="primary" onClick={start} disabled={!release || !horizons.length || !startDate || !endDate || (poolType==="CUSTOM_STATIC_POOL" && members.split(/[\s,]+/).filter(Boolean).length < 20)} style={{ margin: "8px 0" }}>运行 82 个量价因子</Button>{batch && <span>批次：{batch}</span>}
    {summary && <Alert type={summary.status === "FAILED" ? "error" : "info"} showIcon message={`批次 ${summary.status}：${summary.completed}/${summary.requested}`} description={summary.error} style={{ marginBottom: 8 }} />}
    {summary && <Table size="small" pagination={{ pageSize: 8 }} rowKey="alpha_id" dataSource={summary.items} columns={[{title:"因子",dataIndex:"alpha_id"},{title:"计算",dataIndex:"calculation"},{title:"1日 IC",render:(_,r)=>r.evaluations?.["1"]?.summary?.ic_mean ?? "—"},{title:"5日 Rank IC",render:(_,r)=>r.evaluations?.["5"]?.summary?.rank_ic_mean ?? "—"},{title:"有效日期",render:(_,r)=>r.evaluations?.["1"]?.summary?.valid_dates ?? "—"}]} />}
    {summary?.status === "SUCCESS" && <Card size="small" title="相关性、代表因子与保留段" style={{marginBottom:8}} extra={<Button onClick={async()=>{try{setCorrelation(await getFactorCorrelation(batch))}catch(e){setError(String(e))}}}>计算相关性</Button>}>
      {correlation && <><p>完全链接：distance = 1 − |ρ| ≤ 0.2；单日共同证券 ≥ {correlation.min_members}，有效相关日期 ≥ {correlation.min_dates}。簇：{correlation.clusters.map(c=>`[${c.join(", ")}]`).join(" ")}</p>
      <Table size="small" rowKey={r=>`${r.left}-${r.right}`} pagination={{pageSize:8}} dataSource={correlation.pairs} columns={[{title:"因子 A",dataIndex:"left"},{title:"因子 B",dataIndex:"right"},{title:"ρ（保留符号）",render:(_,r)=>r.rho ?? "样本不足"},{title:"有效日期",dataIndex:"effective_dates"}]} />
      {!frozen && <><p>选择代表因子并说明理由后将不可更改；此操作才会开放保留段。</p>{summary.items.map(i=><div key={i.alpha_id}><Checkbox checked={selected.includes(i.alpha_id)} onChange={e=>setSelected(e.target.checked?[...selected,i.alpha_id]:selected.filter(x=>x!==i.alpha_id))}>Alpha {i.alpha_id}</Checkbox>{selected.includes(i.alpha_id)&&<Input placeholder="选择理由" value={reasons[String(i.alpha_id)]||""} onChange={e=>setReasons({...reasons,[String(i.alpha_id)]:e.target.value})} style={{width:360,margin:"0 8px 6px"}} />}</div>)}<Button type="primary" disabled={!selected.length || selected.some(x=>!(reasons[String(x)]||"").trim())} onClick={async()=>{try{await freezeFactorRepresentatives(batch,selected,reasons);setFrozen(true)}catch(e){setError(String(e))}}}>冻结代表因子</Button></>}
      {frozen && <Button type="primary" onClick={async()=>{try{setHoldout((await evaluateFactorHoldout(batch)).holdout_access)}catch(e){setError(String(e))}}}>评价已冻结代表的保留段</Button>}{holdout && <Alert type="info" showIcon message="保留段已访问并留痕" description={`代表因子：${String(holdout.alpha_ids || "")}`} style={{marginTop:8}} />}</>}
    </Card>}
    <Table size="small" pagination={{ pageSize: 12 }} rowKey="alpha_id" dataSource={rows} columns={[
      { title: "编号", dataIndex: "alpha_id" }, { title: "依赖组", dataIndex: "group" }, { title: "预热", dataIndex: "lookback_days" },
      { title: "输入资格", render: (_, r) => r.group === "price_volume" ? "READY" : "PARTIAL" }, { title: "评价", dataIndex: "evaluation_status" },
      { title: "公式", dataIndex: "formula", ellipsis: true },
    ]} />
  </Card>;
}
